version: "3.5"

services:
  node:
    build: server
    container_name: api-server
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - NODE_ENV={NODE_ENV}
      - PORT=8080
      - APP_NAME=api-server
      - SERVER_ROOT=.
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/chat-dev?authSource=admin
      - CHOKIDAR_USEPOLLING=true
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: clutteredcode/mongo-alpine
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    container_name: api-db
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
