version: "3.5"

services:
  node:
    build: .
    container_name: api-server
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=8080
      - APP_NAME=api-server
      - SERVER_ROOT=.
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@api-db:27017/api
      - CHOKIDAR_USEPOLLING=true
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: 'bitnami/mongodb:latest' 
    environment:
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT}
      - MONGODB_DATABASE=api
    container_name: api-db
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
